import {
  Organization,
  Profile,
  Client,
  SecuritySite,
  Guard,
  Supervisor,
  Shift,
  Incident,
  Novedad,
  Inspection,
  Visit,
  SecurityDocument,
  Alert,
  AuditLog
} from '../types/database';

export const INITIAL_ORGANIZATION: Organization = {
  id: 'org-andina-001',
  name: 'Vigilancia & Seguridad Andina S.A.S.',
  nit: '900.842.190-3',
  address: 'Calle 100 # 19A-45, Edificio Paralelo 108, Bogotá D.C.',
  phone: '+57 (601) 745-9800',
  email: 'operaciones@seguridadandina.com.co',
  status: 'ACTIVA',
  created_at: '2024-01-15T08:00:00Z',
};

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'user-superadmin',
    organization_id: 'org-andina-001',
    full_name: 'Alejandro Morales Cifuentes',
    email: 'admin@seguridadandina.com.co',
    phone: '+57 310 456 7890',
    role: 'SUPER_ADMIN',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVO',
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 'user-admin',
    organization_id: 'org-andina-001',
    full_name: 'Ing. Rodrigo Vargas Peña',
    email: 'gerencia@seguridadandina.com.co',
    phone: '+57 311 987 6543',
    role: 'ADMIN_EMPRESA',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVO',
    created_at: '2024-01-15T08:30:00Z',
  },
  {
    id: 'user-dir-ops',
    organization_id: 'org-andina-001',
    full_name: 'Capitán (R) Fernando Mendoza',
    email: 'operaciones.director@seguridadandina.com.co',
    phone: '+57 315 234 5678',
    role: 'DIRECTOR_OPERACIONES',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVO',
    created_at: '2024-01-16T09:00:00Z',
  },
  {
    id: 'user-sup-1',
    organization_id: 'org-andina-001',
    full_name: 'Javier Restrepo Gómez',
    email: 'j.restrepo@seguridadandina.com.co',
    phone: '+57 318 765 4321',
    role: 'SUPERVISOR',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVO',
    created_at: '2024-01-18T10:00:00Z',
  },
  {
    id: 'user-guard-carlos',
    organization_id: 'org-andina-001',
    full_name: 'Carlos Andrés Benítez',
    email: 'carlos.benitez@seguridadandina.com.co',
    phone: '+57 312 345 6789',
    role: 'GUARDA',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVO',
    created_at: '2024-02-01T07:00:00Z',
  },
  {
    id: 'user-client-cc-norte',
    organization_id: 'org-andina-001',
    full_name: 'Dra. Marcela Quintana (Gerente Operaciones CC Norte)',
    email: 'operaciones@ccnorte.com.co',
    phone: '+57 301 222 3344',
    role: 'CLIENTE',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVO',
    created_at: '2024-02-10T11:00:00Z',
  }
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-001',
    organization_id: 'org-andina-001',
    name: 'Centro Comercial Santa Fe & Plaza Norte',
    document: 'NIT 900.561.229-8',
    phone: '+57 (601) 678-2000',
    email: 'seguridad@ccnorte.com.co',
    address: 'Autopista Norte # 185-45, Bogotá',
    status: 'ACTIVO',
    contact_person: 'Marcela Quintana - Jefe de Seguridad Física',
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 'cli-002',
    organization_id: 'org-andina-001',
    name: 'Banco Financiero Internacional - Red Sede Central',
    document: 'NIT 860.007.822-1',
    phone: '+57 (601) 345-8888',
    email: 'seguridad.bancaria@bfi.com.co',
    address: 'Carrera 7 # 72-13, Centro Financiero, Bogotá',
    status: 'ACTIVO',
    contact_person: 'Mayor (R) Gonzalo Díaz - Director de Protección',
    created_at: '2024-01-22T11:30:00Z',
  },
  {
    id: 'cli-003',
    organization_id: 'org-andina-001',
    name: 'Parque Logístico e Industrial Metrópoli Occidente',
    document: 'NIT 901.123.456-4',
    phone: '+57 (601) 890-5000',
    email: 'logistica.segura@metropolioccidente.co',
    address: 'Km 3.5 Vía Funza - Siberia, Cundinamarca',
    status: 'ACTIVO',
    contact_person: 'Ing. Bernardo Valdés - Gerente de Infraestructura',
    created_at: '2024-02-01T08:00:00Z',
  },
  {
    id: 'cli-004',
    organization_id: 'org-andina-001',
    name: 'Clínica Especializada Nueva Esperanza',
    document: 'NIT 830.098.765-2',
    phone: '+57 (601) 520-3000',
    email: 'servicios.generales@clinicaesperanza.org',
    address: 'Calle 127 # 20-18, Usaquén, Bogotá',
    status: 'ACTIVO',
    contact_person: 'Dr. Hernán Arango - Director Administrativo',
    created_at: '2024-02-15T14:00:00Z',
  },
  {
    id: 'cli-005',
    organization_id: 'org-andina-001',
    name: 'Conjunto Residencial Cerros de Torca High-Security',
    document: 'NIT 900.445.671-0',
    phone: '+57 320 891 2345',
    email: 'administracion@cerrosdetorca.com',
    address: 'Carrera 7 con Calle 222, Torca, Bogotá',
    status: 'ACTIVO',
    contact_person: 'Gloria Esperanza Rincón - Administradora PH',
    created_at: '2024-03-01T09:00:00Z',
  }
];

export const INITIAL_SECURITY_SITES: SecuritySite[] = [
  {
    id: 'site-001',
    organization_id: 'org-andina-001',
    client_id: 'cli-001',
    name: 'Centro Comercial Norte — Entrada Principal y Plazas',
    code: 'CCN-01',
    address: 'Autopista Norte # 185-45, Entrada Peatonal 1',
    latitude: 4.7618,
    longitude: -74.0452,
    description: 'Puesto de control perimetral, pasillos comerciales y accesos principales con afluencia masiva.',
    risk_level: 'ALTO',
    status: 'ACTIVO',
    required_guards_count: 6,
    operating_hours: '24/7 (Turnos 12h rotativos)',
    contact_phone: '+57 (601) 678-2010',
    created_at: '2024-01-20T10:15:00Z',
  },
  {
    id: 'site-002',
    organization_id: 'org-andina-001',
    client_id: 'cli-001',
    name: 'Centro Comercial Norte — Bahía Parqueadero Sótano 2',
    code: 'CCN-02',
    address: 'Autopista Norte # 185-45, Sótano Nivel -2',
    latitude: 4.7615,
    longitude: -74.0458,
    description: 'Control vehicular de acceso, salida, rampas y puertas de emergencia de evacuación.',
    risk_level: 'MEDIO',
    status: 'ACTIVO',
    required_guards_count: 4,
    operating_hours: '06:00 - 23:00',
    contact_phone: '+57 (601) 678-2022',
    created_at: '2024-01-20T10:30:00Z',
  },
  {
    id: 'site-003',
    organization_id: 'org-andina-001',
    client_id: 'cli-002',
    name: 'Banco Financiero — Bóveda Principal y Tesorería',
    code: 'BFI-BOV',
    address: 'Carrera 7 # 72-13, Torre Empresarial Piso -1',
    latitude: 4.6565,
    longitude: -74.0583,
    description: 'Puesto de máxima criticidad. Control biométrico, circuito cerrado con monitoreo y guarda armado.',
    risk_level: 'CRITICO',
    status: 'ACTIVO',
    required_guards_count: 8,
    operating_hours: '24/7 Con armamento de dotación',
    contact_phone: '+57 (601) 345-8890',
    created_at: '2024-01-22T12:00:00Z',
  },
  {
    id: 'site-004',
    organization_id: 'org-andina-001',
    client_id: 'cli-002',
    name: 'Banco Financiero — Lobby Central y Molinetes',
    code: 'BFI-LOBBY',
    address: 'Carrera 7 # 72-13, Piso 1',
    latitude: 4.6568,
    longitude: -74.0581,
    description: 'Recepción corporativa, verificación de visitantes, control de carnetización y escáner de metales.',
    risk_level: 'MEDIO',
    status: 'ACTIVO',
    required_guards_count: 4,
    operating_hours: '06:00 - 20:00',
    contact_phone: '+57 (601) 345-8889',
    created_at: '2024-01-22T12:15:00Z',
  },
  {
    id: 'site-005',
    organization_id: 'org-andina-001',
    client_id: 'cli-003',
    name: 'Parque Logístico — Portería 1 Carga Pesada',
    code: 'PLM-PORT1',
    address: 'Km 3.5 Vía Funza - Siberia, Entrada Tractomulas',
    latitude: 4.7230,
    longitude: -74.1950,
    description: 'Inspección de contenedores, precintos de seguridad, báscula camionera y prueba de alcoholemia.',
    risk_level: 'ALTO',
    status: 'ACTIVO',
    required_guards_count: 6,
    operating_hours: '24/7 Ininterrumpido',
    contact_phone: '+57 (601) 890-5011',
    created_at: '2024-02-01T08:30:00Z',
  },
  {
    id: 'site-006',
    organization_id: 'org-andina-001',
    client_id: 'cli-003',
    name: 'Parque Logístico — Bodega Aduanera Sector B',
    code: 'PLM-BOD-B',
    address: 'Km 3.5 Vía Funza - Siberia, Muelle 14 al 28',
    latitude: 4.7235,
    longitude: -74.1945,
    description: 'Custodia de mercancías de alto valor en tránsito y verificación de sellos de aduana DIAN.',
    risk_level: 'CRITICO',
    status: 'ACTIVO',
    required_guards_count: 4,
    operating_hours: '24/7 Con rondas programadas',
    contact_phone: '+57 (601) 890-5020',
    created_at: '2024-02-01T08:45:00Z',
  },
  {
    id: 'site-007',
    organization_id: 'org-andina-001',
    client_id: 'cli-004',
    name: 'Clínica Nueva Esperanza — Urgencias y Triage',
    code: 'CNE-URG',
    address: 'Calle 127 # 20-18, Puerta de Ambulancias y Triage',
    latitude: 4.7080,
    longitude: -74.0490,
    description: 'Control de orden público hospitalario, custodia del personal médico y filtros de acompañantes.',
    risk_level: 'ALTO',
    status: 'ACTIVO',
    required_guards_count: 4,
    operating_hours: '24/7',
    contact_phone: '+57 (601) 520-3015',
    created_at: '2024-02-15T14:30:00Z',
  },
  {
    id: 'site-008',
    organization_id: 'org-andina-001',
    client_id: 'cli-004',
    name: 'Clínica Nueva Esperanza — Farmacia de Alto Costo',
    code: 'CNE-FARM',
    address: 'Calle 127 # 20-18, Bloque C Sótano Farmacéutico',
    latitude: 4.7082,
    longitude: -74.0488,
    description: 'Custodia de medicamentos controlados e inventario crítico.',
    risk_level: 'ALTO',
    status: 'ACTIVO',
    required_guards_count: 2,
    operating_hours: '24/7 Monitoreo fijo',
    contact_phone: '+57 (601) 520-3040',
    created_at: '2024-02-15T14:45:00Z',
  },
  {
    id: 'site-009',
    organization_id: 'org-andina-001',
    client_id: 'cli-005',
    name: 'Cerros de Torca — Portería Blindada Principal',
    code: 'TORCA-POR',
    address: 'Carrera 7 con Calle 222, Entrada Residentes',
    latitude: 4.7950,
    longitude: -74.0280,
    description: 'Garita blindada nivel IV con reconocimiento de placas LPR y barreras automáticas anti-ariete.',
    risk_level: 'MEDIO',
    status: 'ACTIVO',
    required_guards_count: 3,
    operating_hours: '24/7',
    contact_phone: '+57 320 891 2346',
    created_at: '2024-03-01T09:30:00Z',
  },
  {
    id: 'site-010',
    organization_id: 'org-andina-001',
    client_id: 'cli-005',
    name: 'Cerros de Torca — Ronda Perimetral Bosque',
    code: 'TORCA-RONDA',
    address: 'Carrera 7 con Calle 222, Cerramiento Ecológico',
    latitude: 4.7965,
    longitude: -74.0265,
    description: 'Patrullaje motorizado y canino con sensores infrarrojos de intrusión en línea de bosque.',
    risk_level: 'ALTO',
    status: 'ACTIVO',
    required_guards_count: 2,
    operating_hours: '18:00 - 06:00 (Nocturno)',
    contact_phone: '+57 320 891 2350',
    created_at: '2024-03-01T09:45:00Z',
  }
];

export const INITIAL_SUPERVISORS: Supervisor[] = [
  {
    id: 'sup-001',
    organization_id: 'org-andina-001',
    profile_id: 'user-sup-1',
    name: 'Javier Restrepo Gómez',
    employee_code: 'SUP-014',
    phone: '+57 318 765 4321',
    email: 'j.restrepo@seguridadandina.com.co',
    status: 'ACTIVO',
    zone: 'Zona Norte (CC Norte, Torca)',
    created_at: '2024-01-18T10:00:00Z',
  },
  {
    id: 'sup-002',
    organization_id: 'org-andina-001',
    profile_id: 'user-sup-2',
    name: 'Carlos Alberto Henao',
    employee_code: 'SUP-018',
    phone: '+57 316 555 4321',
    email: 'c.henao@seguridadandina.com.co',
    status: 'ACTIVO',
    zone: 'Zona Centro Financiero (BFI)',
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'sup-003',
    organization_id: 'org-andina-001',
    profile_id: 'user-sup-3',
    name: 'Mauricio Quintero Paz',
    employee_code: 'SUP-022',
    phone: '+57 310 999 1122',
    email: 'm.quintero@seguridadandina.com.co',
    status: 'ACTIVO',
    zone: 'Zona Occidente / Siberia (Parque Logístico)',
    created_at: '2024-01-25T11:00:00Z',
  },
  {
    id: 'sup-004',
    organization_id: 'org-andina-001',
    profile_id: 'user-sup-4',
    name: 'Diana Patricia Salazar',
    employee_code: 'SUP-029',
    phone: '+57 314 333 7788',
    email: 'd.salazar@seguridadandina.com.co',
    status: 'ACTIVO',
    zone: 'Zona Hospitalaria & Salud (Clínica Esperanza)',
    created_at: '2024-02-05T09:00:00Z',
  },
  {
    id: 'sup-005',
    organization_id: 'org-andina-001',
    profile_id: 'user-sup-5',
    name: 'Héctor Fabio Ospina',
    employee_code: 'SUP-031',
    phone: '+57 321 888 9900',
    email: 'h.ospina@seguridadandina.com.co',
    status: 'ACTIVO',
    zone: 'Ronda Móvil Reacción Rápida y Apoyo',
    created_at: '2024-02-10T14:00:00Z',
  }
];

export const INITIAL_GUARDS: Guard[] = [
  {
    id: 'guard-001',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-carlos',
    name: 'Carlos Andrés Benítez',
    document_number: 'CC 80.123.456',
    employee_code: 'GRD-101',
    phone: '+57 312 345 6789',
    email: 'carlos.benitez@seguridadandina.com.co',
    position: 'Guarda Operativo Control de Acceso',
    hire_date: '2023-03-15',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-001',
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'guard-002',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-002',
    name: 'Wilson Gabriel Caicedo',
    document_number: 'CC 79.889.012',
    employee_code: 'GRD-102',
    phone: '+57 313 456 7891',
    email: 'w.caicedo@seguridadandina.com.co',
    position: 'Guarda Rondero Motorizado',
    hire_date: '2022-11-01',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-002',
    created_at: '2024-01-20T08:15:00Z',
  },
  {
    id: 'guard-003',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-003',
    name: 'Edgar Mauricio Tovar',
    document_number: 'CC 1.018.452.990',
    employee_code: 'GRD-103',
    phone: '+57 317 654 3210',
    email: 'e.tovar@seguridadandina.com.co',
    position: 'Guarda de Custodia Bancaria Armado',
    hire_date: '2021-06-20',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-003',
    created_at: '2024-01-22T09:00:00Z',
  },
  {
    id: 'guard-004',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-004',
    name: 'Yuly Paola Montaño',
    document_number: 'CC 52.889.334',
    employee_code: 'GRD-104',
    phone: '+57 311 223 3445',
    email: 'y.montano@seguridadandina.com.co',
    position: 'Operadora de Circuito Cerrado CCTV',
    hire_date: '2023-01-10',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-004',
    created_at: '2024-01-22T09:30:00Z',
  },
  {
    id: 'guard-005',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-005',
    name: 'Jhonathan David Becerra',
    document_number: 'CC 1.022.334.891',
    employee_code: 'GRD-105',
    phone: '+57 315 998 8776',
    email: 'j.becerra@seguridadandina.com.co',
    position: 'Inspector de Báscula y Carga',
    hire_date: '2023-05-18',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-005',
    created_at: '2024-02-01T07:00:00Z',
  },
  {
    id: 'guard-006',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-006',
    name: 'Álvaro José Cárdenas',
    document_number: 'CC 14.289.445',
    employee_code: 'GRD-106',
    phone: '+57 318 445 5667',
    email: 'a.cardenas@seguridadandina.com.co',
    position: 'Guarda Seguridad Industrial y Mercancías',
    hire_date: '2022-08-14',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-006',
    created_at: '2024-02-01T07:15:00Z',
  },
  {
    id: 'guard-007',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-007',
    name: 'Mónica Andrea Suárez',
    document_number: 'CC 1.015.678.901',
    employee_code: 'GRD-107',
    phone: '+57 310 112 2334',
    email: 'm.suarez@seguridadandina.com.co',
    position: 'Guarda de Triage Hospitalario',
    hire_date: '2023-09-01',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-007',
    created_at: '2024-02-15T08:00:00Z',
  },
  {
    id: 'guard-008',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-008',
    name: 'Néstor Raúl Zambrano',
    document_number: 'CC 80.998.112',
    employee_code: 'GRD-108',
    phone: '+57 320 334 4556',
    email: 'n.zambrano@seguridadandina.com.co',
    position: 'Custodio de Farmacia y Medicamentos',
    hire_date: '2023-04-12',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-008',
    created_at: '2024-02-15T08:30:00Z',
  },
  {
    id: 'guard-009',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-009',
    name: 'Jorge Eliécer Barreto',
    document_number: 'CC 79.554.210',
    employee_code: 'GRD-109',
    phone: '+57 314 667 7889',
    email: 'j.barreto@seguridadandina.com.co',
    position: 'Operador de Garita Blindada',
    hire_date: '2021-02-10',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-009',
    created_at: '2024-03-01T08:00:00Z',
  },
  {
    id: 'guard-010',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-010',
    name: 'Henry Alexander Pinzón',
    document_number: 'CC 1.030.556.778',
    employee_code: 'GRD-110',
    phone: '+57 322 778 8990',
    email: 'h.pinzon@seguridadandina.com.co',
    position: 'Guía Canino Rondas Forestales',
    hire_date: '2022-04-05',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-010',
    created_at: '2024-03-01T08:15:00Z',
  },
  {
    id: 'guard-011',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-011',
    name: 'Oscar Iván Morales',
    document_number: 'CC 80.445.667',
    employee_code: 'GRD-111',
    phone: '+57 312 990 1122',
    email: 'o.morales@seguridadandina.com.co',
    position: 'Guarda de Relevo y Refuerzo',
    hire_date: '2023-10-15',
    status: 'ACTIVO',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-001',
    created_at: '2024-03-05T09:00:00Z',
  },
  {
    id: 'guard-012',
    organization_id: 'org-andina-001',
    profile_id: 'user-guard-012',
    name: 'Luis Fernando Gaitán',
    document_number: 'CC 1.014.223.556',
    employee_code: 'GRD-112',
    phone: '+57 315 443 2211',
    email: 'l.gaitan@seguridadandina.com.co',
    position: 'Guarda Control Vehicular',
    hire_date: '2023-07-22',
    status: 'VACACIONES',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    assigned_site_id: 'site-002',
    created_at: '2024-03-10T10:00:00Z',
  }
];

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 'shift-001',
    organization_id: 'org-andina-001',
    site_id: 'site-001',
    guard_id: 'guard-001',
    supervisor_id: 'sup-001',
    date: new Date().toISOString().split('T')[0],
    start_time: '06:00',
    end_time: '18:00',
    shift_type: 'DIURNO_6_18',
    status: 'EN_CURSO',
    observations: 'Turno en progreso. Relevo realizado sin anomalías con libro firmado.',
    created_at: '2024-04-01T05:30:00Z',
  },
  {
    id: 'shift-002',
    organization_id: 'org-andina-001',
    site_id: 'site-002',
    guard_id: 'guard-002',
    supervisor_id: 'sup-001',
    date: new Date().toISOString().split('T')[0],
    start_time: '06:00',
    end_time: '18:00',
    shift_type: 'DIURNO_6_18',
    status: 'EN_CURSO',
    observations: 'Control vehicular y supervisión de accesos en sótanos.',
    created_at: '2024-04-01T05:40:00Z',
  },
  {
    id: 'shift-003',
    organization_id: 'org-andina-001',
    site_id: 'site-003',
    guard_id: 'guard-003',
    supervisor_id: 'sup-002',
    date: new Date().toISOString().split('T')[0],
    start_time: '07:00',
    end_time: '19:00',
    shift_type: 'TURNO_12H',
    status: 'EN_CURSO',
    observations: 'Custodia armada de bóveda central. Verificación de armamento realizada.',
    created_at: '2024-04-01T06:30:00Z',
  },
  {
    id: 'shift-004',
    organization_id: 'org-andina-001',
    site_id: 'site-004',
    guard_id: 'guard-004',
    supervisor_id: 'sup-002',
    date: new Date().toISOString().split('T')[0],
    start_time: '07:00',
    end_time: '19:00',
    shift_type: 'TURNO_12H',
    status: 'EN_CURSO',
    observations: 'Operación ininterrumpida de cámaras y recepción de ejecutivos.',
    created_at: '2024-04-01T06:45:00Z',
  },
  {
    id: 'shift-005',
    organization_id: 'org-andina-001',
    site_id: 'site-005',
    guard_id: 'guard-005',
    supervisor_id: 'sup-003',
    date: new Date().toISOString().split('T')[0],
    start_time: '06:00',
    end_time: '18:00',
    shift_type: 'DIURNO_6_18',
    status: 'EN_CURSO',
    observations: 'Control de 48 tractocamiones ingresados hasta el mediodía.',
    created_at: '2024-04-01T05:50:00Z',
  },
  {
    id: 'shift-006',
    organization_id: 'org-andina-001',
    site_id: 'site-007',
    guard_id: 'guard-007',
    supervisor_id: 'sup-004',
    date: new Date().toISOString().split('T')[0],
    start_time: '06:00',
    end_time: '18:00',
    shift_type: 'DIURNO_6_18',
    status: 'EN_CURSO',
    observations: 'Atención a triage de urgencias con alto volumen de pacientes.',
    created_at: '2024-04-01T05:55:00Z',
  },
  {
    id: 'shift-007',
    organization_id: 'org-andina-001',
    site_id: 'site-001',
    guard_id: 'guard-011',
    supervisor_id: 'sup-001',
    date: new Date().toISOString().split('T')[0],
    start_time: '18:00',
    end_time: '06:00',
    shift_type: 'NOCTURNO_18_6',
    status: 'PROGRAMADO',
    observations: 'Turno de noche programado para relevo.',
    created_at: '2024-04-01T07:00:00Z',
  }
];

export const INITIAL_NOVEDADES: Novedad[] = [
  {
    id: 'nov-001',
    organization_id: 'org-andina-001',
    site_id: 'site-001',
    reported_by: 'Carlos Andrés Benítez',
    category: 'seguridad',
    priority: 'CRÍTICA',
    title: 'Puerta de emergencia encontrada abierta en pasillo oriente',
    description: 'Durante la ronda de las 10:15 se detectó la puerta de emergencia número 4 con el pestillo bloqueado por una cuña plástica. No se observaron intrusos. Se procedió a retirar el obstáculo y asegurar el cerrojo electromagnético.',
    event_date: new Date().toISOString().split('T')[0] + ' 10:15',
    status: 'ABIERTA',
    ai_generated: true,
    ai_confidence: 0.98,
    evidence_urls: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80'
    ],
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'nov-002',
    organization_id: 'org-andina-001',
    site_id: 'site-002',
    reported_by: 'Wilson Gabriel Caicedo',
    category: 'infraestructura',
    priority: 'MEDIA',
    title: 'Fuga de agua en tubería de rociadores sótano 2',
    description: 'Goteo continuo cerca a la columna C-14 afectando dos plazas de estacionamiento de visitantes. Se señalizó con conos preventivos y se notificó al área de mantenimiento del centro comercial.',
    event_date: new Date().toISOString().split('T')[0] + ' 08:30',
    status: 'EN_REVISIÓN',
    ai_generated: false,
    evidence_urls: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb186156f?w=600&auto=format&fit=crop&q=80'
    ],
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'nov-003',
    organization_id: 'org-andina-001',
    site_id: 'site-005',
    reported_by: 'Jhonathan David Becerra',
    category: 'vehículo',
    priority: 'ALTA',
    title: 'Tractocamión con precinto roto en inspección de báscula',
    description: 'Vehículo de placas TAZ-892 proveniente de Buenaventura presentó inconsistencia en el precinto aduanero #44901. Se detuvo la entrada al muelle y se solicitó la presencia del inspector de seguridad DIAN.',
    event_date: new Date().toISOString().split('T')[0] + ' 07:15',
    status: 'ASIGNADA',
    ai_generated: false,
    evidence_urls: [
      'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&auto=format&fit=crop&q=80'
    ],
    created_at: new Date(Date.now() - 3600000 * 6).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'nov-004',
    organization_id: 'org-andina-001',
    site_id: 'site-007',
    reported_by: 'Mónica Andrea Suárez',
    category: 'comportamiento',
    priority: 'ALTA',
    title: 'Acompañante exaltado en sala de espera de Urgencias',
    description: 'Familiar de paciente ingresado profirió insultos al personal de enfermería por tiempo de espera. El guarda intervino aplicando protocolo de desescalamiento verbal sin contacto físico. La situación fue controlada.',
    event_date: new Date().toISOString().split('T')[0] + ' 11:40',
    status: 'RESUELTA',
    ai_generated: true,
    ai_confidence: 0.95,
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'nov-005',
    organization_id: 'org-andina-001',
    site_id: 'site-003',
    reported_by: 'Edgar Mauricio Tovar',
    category: 'equipo',
    priority: 'BAJA',
    title: 'Cámara domo PTZ 04 con oscilación intermitente',
    description: 'La cámara de seguridad ubicada sobre el acceso secundario a la bóveda presentó una pérdida de señal de 12 segundos a las 09:14. Volvió a funcionar automáticamente tras reinicio del switch PoE.',
    event_date: new Date().toISOString().split('T')[0] + ' 09:14',
    status: 'RESUELTA',
    ai_generated: false,
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  }
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-001',
    organization_id: 'org-andina-001',
    site_id: 'site-001',
    reported_by: 'Carlos Andrés Benítez',
    incident_type: 'intrusión',
    severity: 'GRAVE',
    title: 'Intento de acceso por azotea del Centro Comercial',
    description: 'Dos sujetos intentaron forzar la escotilla de mantenimiento en la cubierta nororiental a las 02:40 AM. Los sensores perimetrales PIR se activaron de inmediato. El supervisor y la patrulla cuadrante acudieron al lugar en 4 minutos. Los sujetos huyeron arrojando herramientas.',
    incident_date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0] + ' 02:40',
    status: 'EN_INVESTIGACION',
    location: 'Cubierta Azotea Torre B',
    actions_taken: 'Activación de sirena perimetral, alerta a Policía Nacional Cuadrante 12, entrega de grabaciones CCTV a la SIJIN.',
    evidence_urls: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541888946425-d0fbb186156f?w=600&auto=format&fit=crop&q=80'
    ],
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'inc-002',
    organization_id: 'org-andina-001',
    site_id: 'site-005',
    reported_by: 'Jhonathan David Becerra',
    incident_type: 'accidente',
    severity: 'MODERADA',
    title: 'Colisión menor entre montacargas y furgón en patio de maniobras',
    description: 'Durante la operación de descarpe, un montacargas rozó la compuerta trasera del furgón placas WLM-201. Daños materiales leves, sin lesionados ni fuga de combustible.',
    incident_date: new Date(Date.now() - 86400000 * 4).toISOString().split('T')[0] + ' 14:20',
    status: 'ACCIONES_TOMADAS',
    location: 'Patio de Maniobras Bahía 7',
    actions_taken: 'Levantamiento de croquis fotográfico, prueba de alcoholemia negativa al operador, reporte a compañía de seguros.',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'inc-003',
    organization_id: 'org-andina-001',
    site_id: 'site-003',
    reported_by: 'Edgar Mauricio Tovar',
    incident_type: 'amenaza',
    severity: 'CRÍTICA',
    title: 'Paquete sospechoso abandonado en cajero automático anexo',
    description: 'Bolsa negra sin rotular ubicada bajo el teclado del ATM externo. Se activó el protocolo antibombas, se acordonó el área a 50 metros y la unidad antiexplosivos de la Policía descartó artefacto (contenía ropa usada).',
    incident_date: new Date(Date.now() - 86400000 * 7).toISOString().split('T')[0] + ' 18:30',
    status: 'CERRADO',
    location: 'Cajero Automático Exterior Calle 72',
    actions_taken: 'Evacuación perimetral, apoyo de caninos antiexplosivos, reporte a la central de monitoreo bancario.',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    closed_at: new Date(Date.now() - 86400000 * 6).toISOString(),
  }
];

export const INITIAL_INSPECTIONS: Inspection[] = [
  {
    id: 'insp-001',
    organization_id: 'org-andina-001',
    site_id: 'site-001',
    supervisor_id: 'sup-001',
    inspection_date: new Date().toISOString().split('T')[0] + ' 09:30',
    inspection_type: 'RUTINARIA',
    result: 'APROBADA',
    score: 96,
    observations: 'Excelente presentación del personal en puesto. Libro de minuta al día y pulcro. Equipo de radiocomunicación en canal prioritario.',
    items: [
      { id: 'item-1', item: '¿Guarda presente y puntual?', status: 'CUMPLE', observations: 'Presente en posición' },
      { id: 'item-2', item: '¿Uniforme reglamentario completo y carnet visible?', status: 'CUMPLE', observations: 'Impecable' },
      { id: 'item-3', item: '¿Armamento / dotación autorizada y en orden?', status: 'CUMPLE', observations: 'Bastón de mando y linterna' },
      { id: 'item-4', item: '¿Radio de comunicaciones funcionando y batería cargada?', status: 'CUMPLE', observations: 'Señal 5/5' },
      { id: 'item-5', item: '¿Libro de minuta actualizado al minuto?', status: 'CUMPLE', observations: 'Firmado y foliado' },
      { id: 'item-6', item: '¿Puesto de trabajo limpio y ordenado?', status: 'CUMPLE', observations: 'Excelente' },
      { id: 'item-7', item: '¿Sistemas de seguridad y botones de pánico operativos?', status: 'CUMPLE', observations: 'Prueba silenciosa OK' },
      { id: 'item-8', item: '¿Puertas y salidas de emergencia aseguradas?', status: 'NO_CUMPLE', observations: 'Se detectó cuña en puerta 4 y se corrigió de inmediato' }
    ],
    photos: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80'
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'insp-002',
    organization_id: 'org-andina-001',
    site_id: 'site-003',
    supervisor_id: 'sup-002',
    inspection_date: new Date(Date.now() - 86400000).toISOString().split('T')[0] + ' 15:00',
    inspection_type: 'ESPECIAL',
    result: 'APROBADA',
    score: 100,
    observations: 'Inspección de alta seguridad para puesto bancario. Salvoconductos vigentes, munición contada y completa.',
    items: [
      { id: 'item-1', item: '¿Guarda presente y puntual?', status: 'CUMPLE' },
      { id: 'item-2', item: '¿Uniforme reglamentario completo y carnet visible?', status: 'CUMPLE' },
      { id: 'item-3', item: '¿Armamento / dotación autorizada y en orden?', status: 'CUMPLE', observations: 'Revólver Llama .38 SPL con 18 cartuchos' },
      { id: 'item-4', item: '¿Radio de comunicaciones funcionando y batería cargada?', status: 'CUMPLE' },
      { id: 'item-5', item: '¿Libro de minuta actualizado al minuto?', status: 'CUMPLE' },
      { id: 'item-6', item: '¿Puesto de trabajo limpio y ordenado?', status: 'CUMPLE' },
      { id: 'item-7', item: '¿Sistemas de seguridad y botones de pánico operativos?', status: 'CUMPLE' },
      { id: 'item-8', item: '¿Puertas y salidas de emergencia aseguradas?', status: 'CUMPLE' }
    ],
    created_at: new Date(Date.now() - 86400000).toISOString(),
  }
];

export const INITIAL_VISITS: Visit[] = [
  {
    id: 'vis-001',
    organization_id: 'org-andina-001',
    site_id: 'site-001',
    visitor_name: 'Santiago Méndez Rueda',
    visitor_document: 'CC 1.020.345.890',
    visit_type: 'PROVEEDOR',
    vehicle_plate: 'KLU-309',
    entry_time: new Date().toISOString().split('T')[0] + ' 09:15',
    observations: 'Entrega de insumos de aseo para locales piso 2. Se le entregó escarapela #12.',
    badge_number: 'ESC-012',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vis-002',
    organization_id: 'org-andina-001',
    site_id: 'site-005',
    visitor_name: 'Mauricio Gallego Ortiz',
    visitor_document: 'CC 79.443.219',
    visit_type: 'CONTRATISTA',
    vehicle_plate: 'SSX-812',
    entry_time: new Date().toISOString().split('T')[0] + ' 08:00',
    exit_time: new Date().toISOString().split('T')[0] + ' 11:30',
    observations: 'Mantenimiento preventivo de transformadores eléctricos. ARL Sura vigente.',
    badge_number: 'CONTR-05',
    created_at: new Date().toISOString(),
  }
];

export const INITIAL_DOCUMENTS: SecurityDocument[] = [
  {
    id: 'doc-001',
    organization_id: 'org-andina-001',
    client_id: 'cli-001',
    site_id: 'site-001',
    document_type: 'POLIZA',
    name: 'Póliza de Responsabilidad Civil Extracontractual Seguros del Estado',
    file_url: 'https://example.com/poliza-rce-andina.pdf',
    expiration_date: new Date(Date.now() + 86400000 * 5).toISOString().split('T')[0], // 5 days (warning!)
    status: 'POR_VENCER',
    uploaded_by: 'Alejandro Morales Cifuentes',
    created_at: '2023-04-10T10:00:00Z',
  },
  {
    id: 'doc-002',
    organization_id: 'org-andina-001',
    site_id: 'site-003',
    document_type: 'PERMISO_PORTE_ARMAS',
    name: 'Permiso Especial de Porte Colectivo DCCA Comando General FFMM',
    file_url: 'https://example.com/permiso-porte-dcca.pdf',
    expiration_date: new Date(Date.now() + 86400000 * 12).toISOString().split('T')[0], // 12 days
    status: 'POR_VENCER',
    uploaded_by: 'Fernando Mendoza',
    created_at: '2023-05-15T11:00:00Z',
  },
  {
    id: 'doc-003',
    organization_id: 'org-andina-001',
    client_id: 'cli-002',
    document_type: 'CONTRATO',
    name: 'Contrato de Servicios de Vigilancia Bancaria Especializada 2024-2026',
    file_url: 'https://example.com/contrato-bfi-andina.pdf',
    expiration_date: new Date(Date.now() + 86400000 * 365).toISOString().split('T')[0],
    status: 'VIGENTE',
    uploaded_by: 'Rodrigo Vargas Peña',
    created_at: '2024-01-10T09:00:00Z',
  },
  {
    id: 'doc-004',
    organization_id: 'org-andina-001',
    site_id: 'site-005',
    document_type: 'PROTOCOLO',
    name: 'Protocolo de Seguridad Operativa y BASC para Control de Contenedores',
    file_url: 'https://example.com/protocolo-basc-parque.pdf',
    expiration_date: new Date(Date.now() + 86400000 * 180).toISOString().split('T')[0],
    status: 'VIGENTE',
    uploaded_by: 'Javier Restrepo Gómez',
    created_at: '2024-02-01T15:00:00Z',
  }
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'alt-001',
    organization_id: 'org-andina-001',
    site_id: 'site-001',
    alert_type: 'NOVEDAD_CRÍTICA',
    severity: 'CRITICAL',
    title: 'Puerta de emergencia encontrada abierta',
    description: 'Se reportó novedad de prioridad crítica en Centro Comercial Norte (Entrada Principal y Plazas).',
    status: 'ACTIVA',
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'alt-002',
    organization_id: 'org-andina-001',
    site_id: 'site-001',
    alert_type: 'DOCUMENTO_POR_VENCER',
    severity: 'WARNING',
    title: 'Póliza de Responsabilidad Civil vence en 5 días',
    description: 'La póliza RCE del Centro Comercial Norte requiere renovación antes del viernes.',
    status: 'ACTIVA',
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'alt-003',
    organization_id: 'org-andina-001',
    site_id: 'site-010',
    alert_type: 'TURNO_SIN_ASIGNAR',
    severity: 'WARNING',
    title: 'Turno de refuerzo de fin de semana pendiente por asignar',
    description: 'Ronda perimetral de Cerros de Torca requiere asignación de guía canino suplente.',
    status: 'ACTIVA',
    created_at: new Date(Date.now() - 3600000 * 20).toISOString(),
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-001',
    organization_id: 'org-andina-001',
    user_id: 'user-admin',
    user_name: 'Rodrigo Vargas Peña',
    action: 'LOGIN',
    table_name: 'auth.sessions',
    ip_address: '190.144.20.15',
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'audit-002',
    organization_id: 'org-andina-001',
    user_id: 'user-guard-carlos',
    user_name: 'Carlos Andrés Benítez',
    action: 'CREATE',
    table_name: 'novedades',
    record_id: 'nov-001',
    new_data: '{"title": "Puerta de emergencia encontrada abierta", "priority": "CRÍTICA"}',
    ip_address: '186.84.90.11',
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'audit-003',
    organization_id: 'org-andina-001',
    user_id: 'user-sup-1',
    user_name: 'Javier Restrepo Gómez',
    action: 'CREATE',
    table_name: 'inspections',
    record_id: 'insp-001',
    new_data: '{"site": "Centro Comercial Norte", "score": 96, "result": "APROBADA"}',
    ip_address: '190.25.110.84',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'audit-004',
    organization_id: 'org-andina-001',
    user_id: 'user-superadmin',
    user_name: 'Alejandro Morales Cifuentes',
    action: 'AI_ACTION',
    table_name: 'ai_actions',
    new_data: '{"action": "speech_to_novedad", "status": "EJECUTADA"}',
    ip_address: '190.144.20.15',
    created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
  }
];
